LightSotre/Models/Urun.cs
namespace LightSotre.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Urun")]
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            Sepet = new HashSet<Sepet>();
            Satici = new HashSet<Satici>();
            Siparis = new HashSet<Siparis>();
        }

        public int UrunId { get; set; }

        [Required]
        [StringLength(50)]
        public string UrunIsim { get; set; }

        public int Kategore_ID { get; set; }

        public double urunFiyat { get; set; }

        public string urunOzellikler { get; set; }

        [StringLength(1000)]
        public string urunImage { get; set; }

        public virtual Kategore Kategore { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satici> Satici { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis { get; set; }
    }
}

LightSotre/Controllers/UrunsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LightSotre.Models;

namespace LightSotre.Controllers
{
    public class UrunsController : Controller
    {
        private Context db = new Context();
        [AllowAnonymous]
        // GET: Uruns
        public ActionResult Index()
        {
            var urun = db.Urun.Include(u => u.Kategore);
            return View(urun.ToList());
        }

        // GET: Uruns/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Urun.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // GET: Uruns/Create
        public ActionResult Create()
        {
            ViewBag.Kategore_ID = new SelectList(db.Kategore, "KatagoreId", "KategoreIsim");
            return View();
        }

        // POST: Uruns/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UrunId,UrunIsim,Kategore_ID,urunFiyat,urunOzellikler,urunImage")] Urun urun)
        {
            if (ModelState.IsValid)
            {
                db.Urun.Add(urun);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Kategore_ID = new SelectList(db.Kategore, "KatagoreId", "KategoreIsim", urun.Kategore_ID);
            return View(urun);
        }

        // GET: Uruns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Urun.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            ViewBag.Kategore_ID = new SelectList(db.Kategore, "KatagoreId", "KategoreIsim", urun.Kategore_ID);
            return View(urun);
        }

        // POST: Uruns/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UrunId,UrunIsim,Kategore_ID,urunFiyat,urunOzellikler,urunImage")] Urun urun)
        {
            if (ModelState.IsValid)
            {
                db.Entry(urun).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Kategore_ID = new SelectList(db.Kategore, "KatagoreId", "KategoreIsim", urun.Kategore_ID);
            return View(urun);
        }

        // GET: Uruns/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Urun.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // POST: Uruns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Urun urun = db.Urun.Find(id);
            db.Urun.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LightSotre/Views/Uruns/Create.cshtml
@model LightSotre.Models.Urun

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/HomeLayout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Urun</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.UrunIsim, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UrunIsim, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UrunIsim, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Kategore_ID, "Kategore_AD", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Kategore_Id", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Kategore_ID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.urunFiyat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.urunFiyat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.urunFiyat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.urunImage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.urunImage, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.urunImage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.urunOzellikler, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.urunOzellikler, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.urunOzellikler, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LightSotre/Views/Uruns/Delete.cshtml
@model LightSotre.Models.Urun

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/HomeLayout.cshtml";

}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Urun</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kategore.KategoreIsim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategore.KategoreIsim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunIsim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunIsim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.urunFiyat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.urunFiyat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.urunOzellikler)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.urunOzellikler)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LightSotre/Views/Uruns/Details.cshtml
@model LightSotre.Models.Urun

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/HomeLayout.cshtml";

}

<h2>Details</h2>

<div>
    <h4>Urun</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kategore.KategoreIsim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategore.KategoreIsim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunIsim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunIsim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.urunFiyat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.urunFiyat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.urunOzellikler)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.urunOzellikler)
        </dd>
        <dd>
            <div class="tshirt_img"><img src="@Html.DisplayFor(model => model.urunImage)"></div>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UrunId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LightSotre/Views/Uruns/Edit.cshtml
@model LightSotre.Models.Urun

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/HomeLayout.cshtml";

}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Urun</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.UrunId)

    <div class="form-group">
        @Html.LabelFor(model => model.UrunIsim, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UrunIsim, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UrunIsim, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Kategore_ID, "Kategore_ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Kategore_ID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Kategore_ID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.urunFiyat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.urunFiyat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.urunFiyat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.urunImage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.urunImage, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.urunImage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.urunOzellikler, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.urunOzellikler, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.urunOzellikler, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LightSotre/Views/Uruns/Index.cshtml
@model IEnumerable<LightSotre.Models.Urun>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/HomeLayout.cshtml";
}

<p>
    @if (User.IsInRole("a"))
    {
        <a href="@Url.Action("Create", "Uruns")" class="btn btn-primary py-4">Yeni Ürün Ekle</a>
    }
</p>


<div class="container-xxl py-5">
    <div class="container">
        <div class="section-title text-center">
            <h1 class="display-5 mb-5" style="color:sienna">Ürünlerimiz</h1>
        </div>
        <div class="row mt-n2 wow fadeInUp" data-wow-delay="0.3s">
            <div class="col-12 text-center">
                <ul class="list-inline mb-5" id="portfolio-flters">
                    <li class="mx-2 active" data-filter="*">All</li>
                </ul>
            </div>
        </div>
        <div class="row g-4 portfolio-container">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-md-6 portfolio-item @item.Kategore.KategoreIsim wow fadeInUp" data-wow-delay="0.1s">
                    <div class="rounded overflow-hidden">
                        <div class="position-relative overflow-hidden">
                            <img class="img-fluid w-100" src="@item.urunImage" alt="">
                            <div class="portfolio-overlay">
                                <a class="btn btn-square btn-outline-light mx-1" href="@item.urunImage" data-lightbox="portfolio"><i class="fa fa-eye"></i></a>
                                <a class="btn btn-square btn-outline-light mx-1" href=""><i class="fas fa-cart-plus"></i></a>
                            </div>
                        </div>
                        <div class="border border-5 border-light border-top-0 p-4">
                            <r>Urun ismi :</r><r class="text-primary fw-medium mb-2"> @item.UrunIsim</r>
                            <br />
                            <r>Urun Fiyatı :</r><r class="text-primary fw-medium mb-2"> @item.urunFiyat</r>
                            <br />
                            <r>Urun Özellikleri :</r><r class="text-primary fw-medium mb-2">@item.urunOzellikler</r>
                            <br />
                            <br />
                            @if (User.IsInRole("a"))
                            {
                                @Html.ActionLink("Edit", "Edit", new { id = item.UrunId }) <r>|</r>
                                @Html.ActionLink("Delete", "Delete", new { id = item.UrunId }) <r>|</r>
                                @Html.ActionLink("Details", "Details", new { id = item.UrunId })

                            }

                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>